/***
 * Lurking Ninja CodeGen
 * Copyright (c) 2022-2024 Lurking Ninja.
 *
 * MIT License
 * https://github.com/LurkingNinja/com.lurking-ninja.codegen
 */
#if LN_LOCALIZATION
namespace LurkingNinja.CodeGen.Editor
{
    using UnityEngine;

    public partial class CodeGenSettings
    {
        public static bool LocalizationEnabled => instance.localization;
        public static string LocalizationNameSpace => instance.localizationNameSpace;
        public static string LocalizationFilePath => instance.localizationFilePath;
        public static string LocalizationTemplate => instance.localizationTemplate;

        [SerializeField] internal bool localization = true;
        [SerializeField] internal string localizationNameSpace;
        [SerializeField] internal string localizationFilePath = "Assets/Plugins/LurkingNinja/CodeGen/i18n/";
        [SerializeField] internal string localizationTemplate = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated: {0}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine.Localization.Settings;

public static partial class I18N
{{
    public static class {1}
    {{
        private const string @NAME = ""{2}""; 
{3}
    }}
}}";
    }
}
#endif